# docker build --tag redis .

FROM microsoft/windowsservercore

####### PORTS ########## 
EXPOSE 6379 

ENV chocolateyVersion 0.9.9.12
ENV ChocolateyUseWindowsCompression false

RUN @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

RUN choco install -y redis-64 