#docker build --tag rabbitmq .

FROM microsoft/windowsservercore

####### PORTS ########## 
#Main rabbitmq port 
EXPOSE 5672 
#port mapper daemon (epmd) 
EXPOSE 4369 
#Ninet dist listen 
EXPOSE 35197 
#rabbitmq management console 
EXPOSE 15672 

#set the home directory for erlang so rabbit can find it easily 
ENV ERLANG_HOME "c:\program files\erl8.3\erts-8.3"
ENV ERLANG_SERVICE_MANAGER_PATH "c:\program files\erl8.3\erts-8.3\bin"
ENV RABBITMQ_CONFIG_FILE "c:\rabbitmq" 

ENV chocolateyVersion 0.9.9.12
ENV ChocolateyUseWindowsCompression false

RUN @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

COPY rabbitmq.config c:\rabbitmq.config

RUN choco install -y rabbitmq --version 3.6.10

RUN [ "\"c:\\Program Files\\RabbitMQ Server\\rabbitmq_server-3.6.10\\sbin\\rabbitmq-service.bat\"", "disable" ]

CMD [ "\"c:\\Program Files\\RabbitMQ Server\\rabbitmq_server-3.6.10\\sbin\\rabbitmq-server.bat\"" ]